In [ ]:
# clean employee_comp data:
import pandas as pd

data = pd.read_csv("/Desktop/SJ Employee Comp/Employee_Comp_2025.csv")

# load column names

print(data.columns)

Index(['_id', 'Name', 'Department', 'Job Title (as of 12/31/25)',
       'Total Cash Compensation', 'Base Pay', 'Overtime',
       'Sick and Vacation Payouts', 'Other Cash Compensation',
       'Defined Contribution Plan Contributions - City Paid',
       'Medical Dental Vision',
       'Retirement Contributions (Normal Cost) - City Paid',
       'Long Term Disability, Life, Medicare',
       'Misc Employment Related Costs'],
      dtype='object')

In [32]:
# remove columns such as: _id and 'Defined Contribution Plan Contributions - City Paid' (i don't know what that is)
 
data = data.drop(['_id', 'Defined Contribution Plan Contributions - City Paid'], axis = 1)
data.head()

,Name,Department,Job Title (as of 12/31/25),Total Cash Compensation,Base Pay,Overtime,Sick and Vacation Payouts,Other Cash Compensation,Medical Dental Vision,Retirement Contributions (Normal Cost) - City Paid,"Long Term Disability, Life, Medicare",Misc Employment Related Costs
0,Spencer Piercy,Fire,Fire Engineer,"627,120.27","173,484.09","437,337.38",0,"16,298.80","11,471.04","26,424.46","9,105.57",454.88
1,Galvin Charekian,Fire,Fire Captain,"572,532.67","199,071.86","356,760.39",0,"16,700.42","25,836.96","73,045.43","8,277.29",397.62
2,John Barg,Police,Police Lieutenant,"565,327.73","222,985.60","307,351.45",0,"34,990.68",622.32,"81,606.33","8,235.17",416.40
3,Nora Frimann,Attorney,City Attorney U,"532,791.49","370,310.23",0,"157,641.26","4,840.00","18,260.68","77,404.87","9,035.95",369.78
4,Martin Mora,Fire,Fire Engineer,"506,896.82","173,484.09","324,614.67",0,"8,798.06","25,836.96","63,462.40","7,209.80",339.98

In [38]:
# integer columns
columns_to_clean = [
    "Total Cash Compensation", "Base Pay", "Overtime", "Sick and Vacation Payouts",
    "Other Cash Compensation", "Medical Dental Vision", "Retirement Contributions (Normal Cost) - City Paid",
    "Long Term Disability, Life, Medicare", "Misc Employment Related Costs"
]

#remove the columns using lambda
data[columns_to_clean] = data[columns_to_clean].apply(lambda x: x.astype(str).str.replace(',', '', regex=True))

data.head(20)

,Name,Department,Job Title (as of 12/31/25),Total Cash Compensation,Base Pay,Overtime,Sick and Vacation Payouts,Other Cash Compensation,Medical Dental Vision,Retirement Contributions (Normal Cost) - City Paid,"Long Term Disability, Life, Medicare",Misc Employment Related Costs
0,Spencer Piercy,Fire,Fire Engineer,627120.27,173484.09,437337.38,0,16298.80,11471.04,26424.46,9105.57,454.88
1,Galvin Charekian,Fire,Fire Captain,572532.67,199071.86,356760.39,0,16700.42,25836.96,73045.43,8277.29,397.62
2,John Barg,Police,Police Lieutenant,565327.73,222985.60,307351.45,0,34990.68,622.32,81606.33,8235.17,416.4
3,Nora Frimann,Attorney,City Attorney U,532791.49,370310.23,0,157641.26,4840.00,18260.68,77404.87,9035.95,369.78
4,Martin Mora,Fire,Fire Engineer,506896.82,173484.09,324614.67,0,8798.06,25836.96,63462.40,7209.80,339.98
5,Jared Peterson,Police,Police Officer,495002.16,149560.80,327962.99,0,17478.37,11471.04,21535.15,7187.87,371.35
6,Jennifer Maguire,City Manager,City Manager U,478663.24,456014.61,0,0,22648.63,2368.80,99887.79,8424.25,373.82
7,Michael White,Police,Police Lieutenant,478107.07,222576.80,225377.51,0,30152.76,25836.96,81463.49,6908.12,324.78
8,Mathew Walsh,Police,Police Sergeant,474847.99,192524.80,237463.69,0,44859.50,25131.60,70458.41,6861.79,345.49
9,Ken Tran,Police,Police Captain,466996.28,238080.00,191424.80,0,37491.48,25836.96,87113.44,6712.93,319.53
10,Tony Diep,Police,Police Sergeant,458624.47,194622.40,228274.80,0,35727.27,1829.52,71203.94,6681.69,316.52
11,Leonard Lao,Police,Police Lieutenant,457768.46,195016.80,237344.59,0,25407.07,25836.96,71351.07,6591.46,305.35
12,Matthew Tuttle,Fire,Fire Captain,457167.80,199071.86,255256.64,0,2839.30,30600.72,71402.87,6614.22,333.48
13,Carrie Gordon,Police,Police Officer,455277.54,168137.60,258764.78,0,28375.16,11471.04,61514.13,6542.22,337.91
14,Randy Torres,Police,Police Captain,454389.67,254299.20,163246.83,0,36843.64,25836.96,93078.78,6564.22,295.78
15,Alfonso Hernandez,Police,Police Officer,451431.36,161960.00,264234.74,0,25236.62,11471.04,59235.14,6555.99,327.3
16,Richard Galea,Police,Police Sergeant,451055.23,194622.40,231293.83,0,25139.00,11471.04,71203.94,6552.63,315.48
17,Gustavo Perez,Police,Police Lieutenant,444370.15,225438.40,181387.64,0,37544.11,25836.96,82478.07,6401.45,292.4
18,Christian Camarillo,Police,Police Lieutenant,442460.42,222985.60,183211.40,0,36263.42,1829.52,81606.33,6406.71,305.1
19,Jacob Morris,Police,Police Lieutenant,438719.00,225438.40,172567.96,0,40712.64,11471.04,82478.07,6371.66,288.37

In [39]:
# any duplicates? 
print(data.duplicated().sum())

# nulls?
print(data.isnull().sum())

print(data['Total Cash Compensation'].isnull().sum())

# looking good

0
Name                                                  0
Department                                            0
Job Title (as of 12/31/25)                            0
Total Cash Compensation                               0
Base Pay                                              0
Overtime                                              0
Sick and Vacation Payouts                             0
Other Cash Compensation                               0
Medical Dental Vision                                 0
Retirement Contributions (Normal Cost) - City Paid    0
Long Term Disability, Life, Medicare                  0
Misc Employment Related Costs                         0
dtype: int64
0

In [40]:
# rewrite

data.to_csv("/Users/sgaheer/Desktop/SJ Employee Comp/Employee_Comp_2025_clean.csv")